version: "2"
services:
  all-all-aws-connector:
    image: ernestio/all-all-aws-connector:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      CONNECTORS: nat.create.aws,nat.update.aws,nat.delete.aws,network.create.aws,network.delete.aws,route53.create.aws,route53.delete.aws,route53.update.aws,s3.create.aws,s3.update.aws,s3.delete.aws,elb.create.aws,elb.delete.aws,elb.update.aws,vpc.create.aws,vpc.delete.aws,instance.delete.aws,instance.update.aws,instance.create.aws,firewall.create.aws,firewall.update.aws,firewall.delete.aws,ebs_volume.create.aws,ebs_volume.delete.aws,rds_cluster.create.aws,rds_cluster.update.aws,rds_cluster.delete.aws,rds_instance.create.aws,rds_instance.update.aws,rds_instance.delete.aws
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  all-all-fake-connector:
    image: ernestio/all-all-fake-connector:1.11.0
    links:
    - nats
    - redis
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  api-gateway:
    image: ernestio/api-gateway:1.11.0
    ports:
    - 8080:8080
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      JWT_SECRET: GENERATEDJWTSECRET
      NATS_URI: nats://nats:4222
  aws-definition-mapper:
    image: ernestio/aws-definition-mapper:1.11.0
    links:
    - nats
    - redis
    - postgres
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  config-store:
    image: ernestio/config-store:1.11.0
    entrypoint: /go/bin/config-store -config /etc/ernest/config.json
    volumes:
    - ./config/config-store/:/etc/ernest/
    links:
    - nats
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  datacenter-store:
    image: ernestio/datacenter-store:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  definition-mapper:
    image: ernestio/definition-mapper:1.11.0
    links:
    - nats
    - redis
    - postgres
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  execution-adapter:
    image: ernestio/execution-adapter:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  execution-builder:
    image: ernestio/execution-builder:1.11.0
    links:
    - nats
    - redis
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  execution-run-salt-connector:
    image: ernestio/execution-run-salt-connector:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  firewall-creator-vcloud-connector:
    image: ernestio/firewall-creator-vcloud-connector:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  firewall-updater-vcloud-connector:
    image: ernestio/firewall-updater-vcloud-connector:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  generic-adapter:
    image: ernestio/generic-adapter:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  generic-builder:
    image: ernestio/generic-builder:1.11.0
    links:
    - nats
    - redis
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  group-store:
    image: ernestio/group-store:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  instance-creator-vcloud-connector:
    image: ernestio/instance-creator-vcloud-connector:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  instance-deleter-vcloud-connector:
    image: ernestio/instance-deleter-vcloud-connector:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  instance-updater-vcloud-connector:
    image: ernestio/instance-updater-vcloud-connector:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  logger:
    image: ernestio/logger:1.11.0
    volumes:
    - ./logs/:/var/logs/
    - ./config/:/etc/ernest/
    links:
    - nats
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_LOG_CONFIG: /etc/ernest/
      ERNEST_LOG_FILE: /var/logs/ernest.log
      NATS_URI: nats://nats:4222
  monit:
    image: ernestio/monit:1.11.0
    ports:
    - 22000:22000
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      JWT_SECRET: GENERATEDJWTSECRET
      NATS_URI: nats://nats:4222
  nat-creator-vcloud-connector:
    image: ernestio/nat-creator-vcloud-connector:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  nat-updater-vcloud-connector:
    image: ernestio/nat-updater-vcloud-connector:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  nats:
    image: nats
    ports:
    - 4222:4222
  network-creator-vcloud-connector:
    image: ernestio/network-creator-vcloud-connector:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  network-deleter-vcloud-connector:
    image: ernestio/network-deleter-vcloud-connector:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  nginx:
    image: nginx
    ports:
    - 443:443
    volumes:
    - ./config/nginx/ernest.local:/etc/nginx/conf.d/default.conf
    - ./config/nginx/ernest.key:/etc/nginx/conf.d/ernest.key
    - ./config/nginx/ernest.crt:/etc/nginx/conf.d/ernest.crt
    links:
    - api-gateway:api-gateway
    - monit:monit
  postgres:
    image: r3labs/postgres
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
    environment:
      DB_NAME: users,groups,datacenters,services
  redis:
    image: redis
  router-creator-vcloud-connector:
    image: ernestio/router-creator-vcloud-connector:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  router-deleter-vcloud-connector:
    image: ernestio/router-deleter-vcloud-connector:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  service-store:
    image: ernestio/service-store:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  user-store:
    image: ernestio/user-store:1.11.0
    links:
    - nats
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  vcloud-definition-mapper:
    image: ernestio/vcloud-definition-mapper:1.11.0
    links:
    - nats
    - redis
    - postgres
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
  workflow-manager:
    image: ernestio/workflow-manager:1.11.0
    links:
    - nats
    - redis
    - postgres
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      NATS_URI: nats://nats:4222
networks: {}
