version: "2"
services:
  all-all-aws-connector:
    depends_on:
    - config-store
    environment:
      CONNECTORS: nat.create.aws,nat.update.aws,nat.delete.aws,network.create.aws,network.delete.aws,route53.create.aws,route53.delete.aws,route53.update.aws,s3.create.aws,s3.update.aws,s3.delete.aws,elb.create.aws,elb.delete.aws,elb.update.aws,vpc.create.aws,vpc.delete.aws,instance.delete.aws,instance.update.aws,instance.create.aws,firewall.create.aws,firewall.update.aws,firewall.delete.aws,ebs_volume.create.aws,ebs_volume.delete.aws,rds_cluster.create.aws,rds_cluster.update.aws,rds_cluster.delete.aws,rds_instance.create.aws,rds_instance.update.aws,rds_instance.delete.aws,nats.find.aws,networks.find.aws,route53s.find.aws,s3s.find.aws,elbs.find.aws,vpcs.find.aws,instances.find.aws,firewalls.find.aws,ebs_volumes.find.aws,rds_clusters.find.aws,rds_instances.find.aws,internet_gateway.create.aws,internet_gateway.delete.aws,internet_gateways.find.aws,iam_role.create.aws,iam_role.delete.aws,iam_roles.find.aws,iam_policy.create.aws,iam_policy.delete.aws,iam_policies.find.aws,iam_instance_profile.create.aws,iam_instance_profile.delete.aws,iam_instance_profiles.find.aws
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/all-all-aws-connector:3.13.0
    networks:
    - ernest
    restart: always
  all-all-azure-connector:
    depends_on:
    - config-store
    environment:
      CONNECTORS: public_ip.create.azure,public_ip.update.azure,public_ip.delete.azure,public_ips.find.azure,virtual_network.create.azure,virtual_network.update.azure,virtual_network.delete.azure,virtual_networks.find.azure,resource_group.create.azure,resource_group.update.azure,resource_group.delete.azure,resource_groups.find.azure,subnet.create.azure,subnet.update.azure,subnet.delete.azure,subnets.find.azure,network_interface.create.azure,network_interface.update.azure,network_interface.delete.azure,network_inerfaces.find.azure,storage_account.create.azure,storage_account.update.azure,storage_account.delete.azure,storage_accounts.find.azure,storage_container.create.azure,storage_container.update.azure,storage_container.delete.azure,storage_containers.find.azure,virtual_machine.create.azure,virtual_machine.update.azure,virtual_machine.delete.azure,virtual_machines.find.azure,lb.create.azure,lb.update.azure,lb.deletev,lbs.find.azure,sql_server.create.azure,sql_server.update.azure,sql_server.delete.azure,sql_servers.find.azure,local_network_gateway.create.azure,local_network_gateway.update.azure,local_network_gateway.delete.azure,local_network_gateways.find.azure,network_security_group.create.azure,network_security_group.update.azure,network_security_group.delete.azure,network_security_groups.find.azure,sql_database.create.azure,sql_database.update.azure,sql_database.delete.azure,sql_databases.find.azure,availability_set.create.azure,availability_set.update.azure,availability_set.delete.azure,availability_sets.find.azure,managed_disk.create.azure,managed_disk.update.azure,managed_disk.delete.azure,managed_disks.find.azure
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/all-all-azure-connector:3.13.0
    networks:
    - ernest
    restart: always
  all-all-fake-connector:
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/all-all-fake-connector:3.13.0
    networks:
    - ernest
    restart: always
  all-all-vcloud-connector:
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/all-all-vcloud-connector:3.13.0
    networks:
    - ernest
    restart: always
  api-gateway:
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      JWT_SECRET: GENERATEDJWTSECRET
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/api-gateway:3.13.0
    networks:
    - ernest
    ports:
    - 8080:8080
    restart: always
  authenticator:
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      JWT_SECRET: GENERATEDJWTSECRET
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/authenticator:3.13.0
    networks:
    - ernest
    restart: always
  authorization-store:
    depends_on:
    - config-store
    - postgres
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/authorization-store:3.13.0
    networks:
    - ernest
    restart: always
  config-store:
    depends_on:
    - nats
    entrypoint: ./config-store -config /etc/ernest/config.json
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/config-store:3.13.0
    networks:
    - ernest
    restart: always
    volumes:
    - ./config/config-store/:/etc/ernest/
  datacenter-store:
    depends_on:
    - config-store
    - postgres
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/datacenter-store:3.13.0
    networks:
    - ernest
    restart: always
  definition-mapper:
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/definition-mapper:3.13.0
    networks:
    - ernest
    restart: always
  logger:
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      ERNEST_LOG_CONFIG: /etc/ernest/
      ERNEST_LOG_FILE: /var/logs/ernest.log
      JWT_SECRET: GENERATEDJWTSECRET
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/logger:3.13.0
    networks:
    - ernest
    ports:
    - 22001:22001
    restart: always
    volumes:
    - ./logs/:/var/logs/
    - ./config/:/etc/ernest/
  monit:
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      JWT_SECRET: GENERATEDJWTSECRET
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/monit:3.13.0
    networks:
    - ernest
    ports:
    - 22000:22000
    restart: always
  nats:
    image: nats
    networks:
    - ernest
    ports:
    - 4222:4222
    restart: always
  nginx:
    image: nginx:1.13.5-alpine
    networks:
    - ernest
    ports:
    - 443:443
    restart: always
    volumes:
    - ./config/nginx/ernest.local:/etc/nginx/conf.d/default.conf
    - ./config/nginx/ernest.key:/etc/nginx/conf.d/ernest.key
    - ./config/nginx/ernest.crt:/etc/nginx/conf.d/ernest.crt
  postgres:
    environment:
      DB_NAME: users,projects,environments,usage,authorizations,policies
    image: postgres:9.6.5-alpine
    networks:
    - ernest
    restart: always
    volumes:
    - ./config/postgres:/docker-entrypoint-initdb.d
    - ./postgres/data:/var/lib/postgresql/data
  scheduler:
    depends_on:
    - config-store
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/scheduler:3.13.0
    networks:
    - ernest
    restart: always
  service-store:
    depends_on:
    - config-store
    - postgres
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/service-store:3.13.0
    networks:
    - ernest
    restart: always
  usage-store:
    depends_on:
    - config-store
    - postgres
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/usage-store:3.13.0
    networks:
    - ernest
    restart: always
  user-store:
    depends_on:
    - config-store
    - postgres
    environment:
      ERNEST_CRYPTO_KEY: CRYPTO_KEY_TEMPLATE
      ERNEST_EDITION: community
      NATS_URI: nats://nats:4222
    image: quay.io/ernest/user-store:3.13.0
    networks:
    - ernest
    restart: always
networks:
  ernest:
    driver: bridge
